### ISSUE TITLE
Wordpress plugin to enable featured image to be pulled through via RSS

### ISSUE THREAD

**Issue by alimanfoo** [wtchg-kwiatkowski/observatory-web#106]
Implement a wordpress plugin as discussed.

**Comment by leehart** [comment]
A functionally-almost-equivalent plugin has been written and tested on my local dev. I just need to work out the best way to test and deploy it in production.
It's very diddy... I was going to paste it here, but I don't like all those eyes! THE EYES!!!!!!!!
