### ISSUE TITLE
Genome browser QA

### ISSUE THREAD

**Issue by alimanfoo** [wtchg-kwiatkowski/observatory-web#113]
This epic is intended to provide an umbrella for QA work on the genome browser. I.e., do some intensive testing, record and fix usability issues and bugs. 

Suggest to do a round of UI testing, both ourselves and whoever else we can rope into it, then collect issues and put all issues that arise under this epic.

**Comment by alimanfoo** [comment]
cc @benjeffery, @leehart, for discussion. As for #114 my suggestion would be for Lee to lead a round of user testing, doing a load of testing himself and also coordinating feedback from anyone else who can spare time and recording all issues in github under this epic. Then either or both of you could work at resolving issues that arise.

**Comment by benjeffery** [comment]
I note that I never got round to https://github.com/cggh/panoptes/issues/517 although as this is mostly a mobile/tablet issue it might not be important.

**Comment by leehart** [comment]
Am I right in thinking that this issue and its siblings (#115, #114, #115, 116) have served their purpose and can be safely closed?
(Considerable QA work has been carried out in those focus areas, although I doubt it can ever be realistically called thoroughly complete, until the code is flawless and all other things are permanent.)
Exhibit A: 250 issues logged
Exhibit B: https://github.com/wtchg-kwiatkowski/observatory-web/blob/master/QAFs-milestone1.md
I suppose we can create another bunch of QA epics when the need arises... Or is that risky? 
Or does this stick around in perpetuity, or at least until all the issues gathered under this QA epic have been resolved, or does it periodically become rejuvenated with the tears of freshly logged QA issues?

**Comment by benjeffery** [comment]
I'm happy to consider these as time-limited focussed QA passes that can now be closed. It doesn't mean we stop logging issues, and if we have an area of concern we can launch a new epic of focussed QA.
