### ISSUE TITLE
Updates to blog writing style guide

### ISSUE THREAD

**Issue by alimanfoo** [wtchg-kwiatkowski/observatory-web#117]
Some suggestions to add to the style guide:
* [ ] The first paragraph will get pulled through to the blog index page, let people know they should write with that in mind.
* [ ] Images of charts/plots are static. Where possible they should have a link to a page with the dynamic plot/chart.

**Comment by benjeffery** [comment]
Done: https://docs.google.com/document/d/1lsktOCntFrp6NanbhN0Bxp8QCgSOZPvBTES_dtM0rtM
