### ISSUE TITLE
Genome Browser: The animated DNA molecule loading thing has no purpose when things aren't loading.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#127]
(Maybe only show when loading.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button]

**Comment by leehart** [comment]
I like the current one, but there might be an even prettier DNA-like loading animation.
Maybe something more like:
- https://loading.io/spinner/dna/
- https://codepen.io/SofiaSergio/pen/OzVbpo
(Suits the genomic-data-Hirstian vibe, and gives an almost 3D feel.)

**Comment by benjeffery** [comment]
I don't see a big reason to change anything here.

**Comment by leehart** [comment]
It's a small reason: removing stuff from the page when it's not being used or serving a function allows the user to focus on the things on the page that matter. It's the principle of removing superfluous clutter from the page.
I suppose the reason to keep things the same would be to trade off expending resources with a perceived gain in UI/UX quality.
I doubt it would take much to hide (or even fade in / fade out) the animated DNA instead of simply stopping the animation. I'm happy to try that myself, unless there's another reason for keeping the static DNA-ish image there?
