### ISSUE TITLE
Genome Browser & Table-based Browser: Lack of navigation context, except for subtle under-lining of "Viewer", which is orange next to orange, which is bad/zero contrast. 

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#129]
(Maybe add breadcrumb.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button]

**Comment by leehart** [comment]
Also in Table-data Browser
HOME [tab] > Explore genomic data through the Viewer [heading] > View samples [button] > [table-data browser]

**Comment by benjeffery** [comment]
Will prob be fixed by the IA changes in the pipe.

**Comment by benjeffery** [comment]
I consider this fixed by the recent IA changes. Moving to review.

**Comment by leehart** [comment]
Yep, I'm satisfied that the added breadcrumb solves this issue.
