### ISSUE TITLE
Genome Browser: Closing a channel causes a dramatic error.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#149]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button]

**Comment by leehart** [comment]
I have also witnessed this (closing channels) working within the same version, after doing other things, but it consistently breaks from the starting position.

**Comment by benjeffery** [comment]
This issue was moved to cggh/panoptes#1132
