### ISSUE TITLE
Genome Browser: Grey-out the "COPY SEQUENCE" button until sequence is not summarized, and provide tooltip "Copy sequence when sequence is not zoomed-out (summarized)."

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#155]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Ref. Seq. [channel] > i [button] > [channel information/legend]

**Comment by leehart** [comment]
There is no obvious indication of when the sequence is or isn't being summarized.

**Comment by benjeffery** [comment]
This would mean checking and rendering the legend on every RAF tick. I don't see enough benefit for the perf hit.

**Comment by leehart** [comment]
I wonder if there is at least a way to indicate whether the sequence is or isn't being summarised, without a performance hit, to at least mitigate this issue.
Obviously the sequence isn't being summarised when the individual ATCG letters can be seen, but there is evidently a point before that zoom level when it is still possible to use the `copy sequence` feature.
