### ISSUE TITLE
Genome Browser: Make the "COPY SEQUENCE" button look more like a button.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#156]
(Maybe put an icon next to it, or a line around it.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Ref. Seq. [channel] > i [button] > [channel information/legend]

**Comment by benjeffery** [comment]
Does this also apply to "ADD FILTER" "ADD/REMOVE TRACKS" et al?

**Comment by leehart** [comment]
I suppose so.
I suppose if an icon was added to the `ADD/REMOVE TRACKS` and `COPY SEQUENCE` buttons, that might suffice.

(The `ADD FILTER` button already has an icon, so it looks more consistent with the other buttons in the menu, etc.)

I image that if the buttons that are in the track info and config areas had some sort of line around them, they would appear more separate from each other, and would look (for want of a better word) more `buttony`. I don't see this issue with the buttons in the left menu, because they all have icons and are in a vertical arrangement.
However, I also half-expect that those areas will look even more cluttered with lines around the buttons. Perhaps reversing them might work better: blue background with white text and white icons.

**Comment by leehart** [comment]
Verified on staging.
(Adding an icon to the "ADD/REMOVE TRACKS" button, etc., or otherwise changing the overall style of the buttons ought to be logged as separate issue, I reckon.)
