### ISSUE TITLE
Genome Browser: The legend ("i" info section) for the Genes channel shows a thick horizontal black line for the gene, but it is not entirely clear that the black line in the visualisation spans the blue coding sequences (it only appears between them).

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#159]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Genes [channel]

(Maybe make it look like the line goes underneath the blue blocks.)

**Comment by leehart** [comment]
While I get what you mean too, the issue seeks to improve the consistency of visual symbolism, to communicate our information and representations more clearly. (Nothing to do with education.)

**Comment by leehart** [comment]
It occurs to me that the black line comes to represent a non-coding sequence portion of the gene, which might or might not be intended. Would it make sense to relabel "Gene" to "Non-coding sequence"?

**Comment by benjeffery** [comment]
The space between genes is also "Non-coding sequence", so it cannot be re-labelled to that. I guess one solution would be to add some blue bits to the black line in the key.

**Comment by leehart** [comment]
Is there a reason why my original idea of having the black line show through the blue blocks in the visualisation wouldn't solve it?

**Comment by leehart** [comment]
Having the black like show through the blue blocks might look a bit messy.
And adding some blue bits to the black line in the key might be a bit confusing, less pure/clear.

I think I have a better idea: how about just changing the colour of the "Gene" line to blue, rather than black?
Black is quite a harsh colour, and the non-coding gene line is already distinguished by being thinner than the coding-gene portions. Being the same colour (I suggest blue, although other genome browsers simply use black for both parts) would give the needed indication that the gene spans the full width and is connected to the other parts.

**Comment by leehart** [comment]
Verified on staging, although the vertical line is missing (despite being OK on local, as shown in shot above.) Will log new issue.
