### ISSUE TITLE
Genome Browser: When you click on a variant triangle, and you're taken to the variant info, and you press the "SHOW IN GENOME BROWSER" button, you lose all your previously added channels along with all of their configurations, custom filters, etc.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#162]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Variants [channel]

**Comment by leehart** [comment]
(This problem also occurs through other paths to the variant info page, via other Variant channel track clickables.)

**Comment by benjeffery** [comment]
This is "works as intended" although maybe the mechanism from the gene finder could be reused. Instead of opening a genome browser this opens the most recent genome browser if there was one.

**Comment by leehart** [comment]
I couldn't find one either #317
