### ISSUE TITLE
Genome Browser: An error occurs when selecting the "Position" option from the "Colour By:" menu.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#164]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Variants [channel] > [cog button] > [channel configuration]

**Comment by benjeffery** [comment]
This issue was moved to cggh/panoptes#1142

**Comment by benjeffery** [comment]
Reopening as actually a configuration error

**Comment by leehart** [comment]
Verified as fixed on staging.
Alas, another bug has been detected in the area while testing. (I'll log it.)
