### ISSUE TITLE
Genome Browser & Table-data Browser: The collapse/expand icon button changes to a hamburger icon, which is probably confusing.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#174]
(Maybe use an icon that depicts a side-menu.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Variants [channel] > [cog button] > [channel configuration] > ADD FILTER [button] > [dialog]

**Comment by leehart** [comment]
Also in Table-data Browser
HOME [tab] > Explore genomic data through the Viewer [heading] > View samples [button] > [table-data browser] > [side-menu] > ADD FILTER [button]

**Comment by leehart** [comment]
Also 
HOME [tab] > Explore genomic data through the Viewer [heading] > View samples [button] > [table-data browser] > PIVOT TABLE [button]

Similar to or same as #126

**Comment by benjeffery** [comment]
I don't understand this one - I thought the hamburger menu depicted a side menu?

**Comment by leehart** [comment]
It might depict a side-menu in the contemporary Google theme, but I expect many users would only expect to see one on a page, and that it would be the main menu. Obviously personal interpretation varies...

Judging from the Wikipedia article, I might be able to cherrypick some conventional interpretations...

1. `placed typically in a top corner`
2. `suggestive of a list`
3. `results in a menu being revealed (sliding out or popping up)`
4. `to save space on smaller devices`

Hmm... Inconclusive.
Anyhow, I was imagining something like this might be more appropriate / less potentially-confusing https://thenounproject.com/term/side-menu/108859/

btw, @georgebusby 
From https://en.wikipedia.org/wiki/Hamburger_button
aka "hamburger, sandwich, hotdog, pancake, tribar (or triple bar) double oreo or options button"

lolz: "the wider hamburger button may be reduced to three vertically stacked dots (displayed as a tri-colon or vertical ellipsis ⋮ ), from which it may also be described as a **kebab**. In the Microsoft Office 365 platform, a similar application menu consisting of three rows of three squares is displayed, which is informally described as the **waffle** by its users."

In my mind this is similar to my previous nitpick about us having both a "hamburger/hotdog" and a "kebab" on the same page (actually in the same menu-bar). The general principle is to reduce the ambiguity about what the icon-button will do, before an inexperienced user clicks on it.

Just having one hamburger menu is often frowned upon in UX circles, let alone two, e.g. https://ux.stackexchange.com/questions/76459/use-of-two-hamburger-menus-in-mobile-app

Try telling that to Google News, and Gmail, who are currently sporting a hamburger AND a .... "waffle"?!

**Comment by leehart** [comment]
Google Maps demonstrates a nice combo of hamburger and side-menu control, imo

![collapse-side-panel](https://user-images.githubusercontent.com/4256466/45230743-c5194500-b2c1-11e8-8ff5-66fb90b30461.png)
