### ISSUE TITLE
Genome Browser: Clicking on the "ADD/REMOVE TRACKS" button doesn't do anything for the initial channels, initially.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#175]
For channels that are added by the user, it opens a track-adding dialog.

(Maybe hide the "ADD/REMOVE TRACKS" button when it doesn't apply, or allow tracks on the initial channels to be changed by the user.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Variants [with FST] [channel(s)] > [cog button] > [channel configuration]

**Comment by leehart** [comment]
Since the button seems to *sometimes* open the track-adding dialog for initial channels, I expect this is a glitch rather than a superfluous button.

**Comment by benjeffery** [comment]
This issue was moved to cggh/panoptes#1138
