### ISSUE TITLE
Genome Browser: The gene visualisation (gene line and coding sequence blue block) disappear at a high zoom level.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#179]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Genes [channel]

**Comment by benjeffery** [comment]
Fetching logic needs tweaking for cases where gene straddles fetch block. See https://github.com/cggh/panoptes/blob/master/webapp/src/js/components/panoptes/genome/tracks/AnnotationChannel.js#L107

**Comment by benjeffery** [comment]
This issue was moved to cggh/panoptes#1140
