### ISSUE TITLE
Genome Browser: Remove the subcategory classification text "- Properties" from the track names under "tracks to display".

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#184]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > ADD CHANNELS [button] > [add channel] > channel config > ADD/REMOVE TRACKS [button]

**Comment by benjeffery** [comment]
Similar to the other "Properties" group issues.

**Comment by leehart** [comment]
"- Properties" also appears in the "channel(s) to add" list, prior to add/remove tracks.
