### ISSUE TITLE
Genome Browser: The user can add more than one of the same track, and there are no individual track settings.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#187]
(Maybe prevent users from adding more than one of the same track.)

FWIW, I reckon this is mostly harmless, and the worse-case scenario I can imagine is it potentially causing the user some minor confusion, which (if that happened) could be easily remedied. 
I'd understand/be content with a won't-fix decision.

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > ADD CHANNELS [button] > [add channel] > channel config > ADD/REMOVE TRACKS [button]

**Comment by leehart** [comment]
There may be some use for this that I hadn't discovered, perhaps when combined with the feature that allows users to change the colour of any track.

**Comment by benjeffery** [comment]
Yeah, the idea here was that you might want to have two copies of a track at different Y scales for example. To do so you would open 2 and change them to how you like, so I'm closing this.
