### ISSUE TITLE
Genome Browsers: Typing into the Search text-box on the track-adding dialog/modal causes an error.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#188]
HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > ADD CHANNELS [button] > [add channel] > channel config > ADD/REMOVE TRACKS [button]

I believe I've witnessed it work sometimes, in the same version, but it consistently breaks from a starting position.

**Comment by leehart** [comment]
Probably the same as #220

**Comment by benjeffery** [comment]
Fixed as part of https://github.com/cggh/panoptes/issues/1131

**Comment by leehart** [comment]
Verified as fixed on staging.
...Alas, two Hydra issues have spawned in its wake.
