### ISSUE TITLE
Genome Browser: The "COPY SEQUENCE" feature does not actually copy the sequence to the user's clipboard

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#192]
...as one (I) might assume. It just shows the sequence in a tooltip.

HOME [tab] > Explore genomic data through the Viewer [heading] > View genome [button] > Ref. Seq. [channel] > i [button] > [channel information/legend]

 (If it is possible to copy to the clipboard, maybe do that and note: "Copied to clipboard: AAAAT". If that isn't possible at this time, maybe relabel this button/action to something like "SHOW SEQUENCE STRING".)

**Comment by benjeffery** [comment]
Could use https://github.com/feross/clipboard-copy would have to get around the async events in react though, as clip access is only allowed as a direct consequence of a click event.

**Comment by leehart** [comment]
GGTGGTAGCATAATGAATTTTGGAGATGTTGATAATAATA
Verified on staging!
