### ISSUE TITLE
Table-data Browser: In the column-picking dialog, remove the sub-category label "Properties" and the expand/collapse control.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#223]
(Keep the add-all-columns and remove-all-columns buttons/features.)

HOME [tab] > Explore genomic data through the Viewer [heading] > View samples [button] > [table-data browser] > PICK COLUMNS [button] > column-picking dialog

**Comment by benjeffery** [comment]
Properties is the default group name. Do you mean to special case that group into not having its title shown?

**Comment by leehart** [comment]
Yes, i.e. if Properties is the only group being shown, then don't show the title "Properties" and don't provide the expand/collapse control.

I think it's potentially confusing (it doesn't mean anything) to users who aren't familiar with the inner workings and terminology of the webapp. It doesn't add any significant clarification, and it potentially detracts/baffles.

I suppose a slight improvement would be to rename it "Columns", which ought to be a more familiar term in the context of a "table", but I would still prefer to see it and the collapse-toggle removed, because the interface would then be less complicated and look cleaner, stripped of unnecessary/superfluous/distracting stuff.
