### ISSUE TITLE
Table-data Browser: On the table-pivoting page, remove the "Properties" category heading from the "Column" and "Row" select menus.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#228]
HOME [tab] > Explore genomic data through the Viewer [heading] > View samples [button] > [table-data browser] > PIVOT TABLE [button]

**Comment by benjeffery** [comment]
This has been mentioned in a few issues. Grouping some columns might make this look like it makes more sense. Properties is the default group, when it is the only group it can look odd.
