### ISSUE TITLE
Resistance Map: There should be more distinction between the pop-up information about a site versus information about a region.

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#256]
(It's easy to accidentally click on a region instead of a site.)

(Maybe change the region popup's "MORE" button to "REGION INFO" to contrast with the "SITE INFO" button.)

It would be cool if the site circle or region polygon had some kind of border colour-change/highlight when clicked on.

HOME [tab] > Explore genomic data through the Viewer [heading] > View resistance map [button]

**Comment by benjeffery** [comment]
Now regions are de-emphasised we can make them non-clickable
