### ISSUE TITLE
Sitewide breadcrumb

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#279]
Add a breadcrumb component sitewide.

**Comment by leehart** [comment]
Not sure if this is a bug or a feature, but I just noticed the Ubuntu website sometimes shows multiple breadcrumbs for the same page. (Personally I worry this might be a little odd, potentially confusing, but interesting nonetheless... An alternative to the path-history approach, to the multiple roads-to-Rome problem.)

![ubuntuwebbreadcrumbs](https://user-images.githubusercontent.com/4256466/45600626-d10ab280-b9f7-11e8-8d31-434972e81a6a.png)
