### ISSUE TITLE
Clicking on the "Read more..." link doesn't scroll to the top of the article page

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#290]
E.g.
Home [page] > ALL ARTICLES [button]
Scroll right to the bottom of the page, and click on the "Read more..." link for the very last article.
Notice that when the article page loads, the page is still scrolled right to the bottom.
(It should be scrolled to the very top.)

**Comment by benjeffery** [comment]
This is a general problem across analysis pages.
