### ISSUE TITLE
Breadcrumb trail needs a "Sites" crumb

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#296]
Otherwise the trail implies that a site is one of the "Geographic Regions"

[home icon]  >  Analysis  >  Resistance in P.f  >  Geographic Regions  >  Kinshasa

**Comment by benjeffery** [comment]
This would mean adding a sites page.

**Comment by leehart** [comment]
It seems like there should be support for crumbs that aren't actually pages.

Imagine:
[home icon] > Analysis > Resistance in P.f > Geographic Regions > Sites > Kinshasa
...where Sites isn't actually a link to a Sites page! (:boom:)

Sure, the current mechanism might require a Sites page in order to feature as a crumb, but maybe we can design a new mechanism, or develop the current mechanism, so that we can have a Sites crumb _without_ requiring a Sites page.

Are there plans/requirements for a Sites page? Does it make sense to have a Sites page anyway?

I suppose Kinshasa is technically a geographic region, but I don't think that implication is intended, and I doubt it's compatible with the webapp's lexicon. Actually, I'm still not sure, myself, what the webapp means by "region"! But it makes sense that Sites are in Regions, and I don't expect the user would care if there wasn't actually Sites page, as long as the trail of crumbs seemed to make sense.

**Comment by benjeffery** [comment]
After discussion we decided to add the region before the site in the breadcrumb.
