### ISSUE TITLE
Resistance Map: The initial site marker dots are difficult to distinguish and click on individually

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#298]
E.g.
Home [page] > Analysis [heading] > View resistance map [button] > Artemisinin [radio option]

(At lowest zoom.)

I doubt that adding a tooltip would help much either, and might actually exacerbate click-targeting, but would help identify and distinguish sites.

(Obviously the user can zoom in to alleviate / workaround the issue.)

I wonder whether removing the clickable functionality at low-zoom might help.

There is also no explanation of what the dots are, since the introduction refers to sized-circles rather than dots:
```
The size of the circle indicates the number of samples collected for that site.
```

Related/Duplicate: #253 

Separate issue (to be logged), regions are no longer shaded, but it says:
```
Regions are shaded by resistance status.
```

**Comment by leehart** [comment]
Actually, I've just realised that it might be impossible to actually click on a site marker at low-zoom. The hand cursor might only relate to the clickable region polygon.

Maybe this adds weight to providing some sort of hover-effect to show the user what they are about to click on, to resolve the ambiguity and avoid confusion.

**Comment by benjeffery** [comment]
#253 will fix this.

**Comment by leehart** [comment]
It feels like problems and their potential solutions are being conflated, e.g. this issue was closed due to an anticipated fix for another issue that hasn't happened yet, and another issue (#155) was closed because one potential solution would cause a relatively worse problem.

Shouldn't an issue remain open as long as it is still an issue, and only be closed when it is either fixed or invalidated? It depends on how we want to manage issues, I guess, but it seems premature to me. Obviously reducing the bug count gives good feels.

@alimanfoo Any feels on this?

**Comment by benjeffery** [comment]
#253 is "MUST" so we are committed to it, so I think of this ticket as a dupe of #253, I close dupes.
