### ISSUE TITLE
Resistance Map: The "MORE" button on the all drugs map site popups is ambiguous (and inconsistent)

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#301]
Home   >  Analysis  >  Resistance in P.f  >  Geographic Regions  >  Map of sites
Ensure "All drugs" is selected.
Click on a site marker.
See that there is a "MORE" button.

(Maybe relabel as "SITE INFO", which would also be consistent with the single drug map site popups.)

**Comment by georgebusby** [comment]
Good call - i've switched MORE to REGION INFO on the regionChloroplethTooltip.html

**Comment by benjeffery** [comment]
I think siteOnClickTooltip.html needed an edit for this hence: 1b705452b906c653929bdc02d96b14e8c3dbd9e8
