### ISSUE TITLE
Clicking on a drug in the drug resistance barchart for a site leads to drug resistance page for the region

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#303]
E.g.
Home [page] > Analysis [heading] > View resistance map [button] > [site marker, e.g. Navrongo] > More [button] > Navrongo [page]
Find the "Predicted antimalarial drug resistance" barchart.
Click on a drug.
See that it loads the drug resistance page for the region.

The user is not given any prior reason to expect this behaviour, even if it's useful.
It seems more likely, to me, that the user would expect their click action to lead to the drug page, since they're clicking on a drug.

(Maybe change to lead to the appropriate drug page.)

(Maybe also add a tooltip, to warn the user what their click will do.)

(I suspect this is a copy-paste relic from another barchart template, where the items are regions.)

**Comment by benjeffery** [comment]
This was intended behaviour. We don't have site/drug so region drug was the closest thing. Happy to change if it is confusing though.

**Comment by leehart** [comment]
I vote for changing it to go to each drug page, e.g. Drugs > Artemisinin, ideally with a tooltip hint.
There's a barchart for the drug-in-region pages on the drug page, so at least it would be less "lucky dip", imo.
What thinks @georgebusby ?

**Comment by benjeffery** [comment]
George says drug.
