### ISSUE TITLE
Table-data Browser: The text-search feature does not search all text-searchable columns

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#305]
E.g.
On the "Samples Table" page, the text-search only searches the `Sample ID` column.
On the "Variants Table" page, only the `Change` and `Position` columns are searched.

**Comment by leehart** [comment]
Currently `ConfigStore.js` loads the list of columns from the `quickFindFields`, and defaults to just the `table.primKey` when no `quickFindFields` are specfied, i.e.
```
table.quickFindFields = table.quickFindFields ? _map(table.quickFindFields.split(','), (s) => s.trim()) : [table.primKey];
```

I'm wondering whether we should change this behaviour to be more automatic, or whether we should simply manually specify the columns that we want to include in the datatable's settings for `quickFindFields`, which would be a config change, rather than a change to the core code.

**Comment by benjeffery** [comment]
I guess if quick find is empty it could search text fields, but we'd have to be careful to set it for large tables as it easily leads to query timeouts. I'd just change the config for now.
