### ISSUE TITLE
The variant page content is incomplete

### ISSUE THREAD

**Issue by leehart** [wtchg-kwiatkowski/observatory-web#317]
Currently says:
```
If this is a variant of note a section here will discuss it, linking to other areas.

A map of the variants geographic spread (WIP)
```

**Comment by leehart** [comment]
Also, the "SHOW IN GENOME BROWSER" button is appearing in the extreme bottom right-hand corner.

**Comment by benjeffery** [comment]
When this page is complete replace the tooltip on the variant list table with a click through to this page.

**Comment by georgebusby** [comment]
the plan is to show allele freq pie charts on the world map for a given variant. this is done quite often with human data: http://hgdp.uchicago.edu/cgi-bin/alfreqs.cgi?pos=136312909&chr=chr2&rs=rs11903319&imp=false 

suggest a neutral colour scheme though - i guess whatever colours you'll use on the genotypes channel
