### ISSUE TITLE
Genome browser should open default tracks if never opened, if not should re-use existing state.

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#354]
For example the menu button for the genome browser does not show any channels.

**Comment by benjeffery** [comment]
For this I intended to make `observatory` specific changes (for now) whereby any opening of a component will re-use an existing component, but with the props merged. New props will take precedence. This will be a simple shallow merge - for example on the genome browser child channels will be replaced rather than appended/merged with existing channels. I think this will work best given our use cases of showing the user genotypes for certain genes etc. However where there are no children (for example coming from a variant) the existing channels will be used.

**Comment by benjeffery** [comment]
Note this will also effect the behavior of tables and other components. If a filter has been placed on variants and then one clicks the variant table button in the top nav then the filter will still be there.

**Comment by leehart** [comment]
On the surface, that seems like it might be in-line with user expectation (consistency).
I suspect we might still see some unwanted side-effects though.

**Comment by benjeffery** [comment]
Doing this as a function of component gets really messy, so I hope this works. Note that a button can always clear the filter etc. by giving the prop on component open.

**Comment by leehart** [comment]
Re-using existing components also seems efficient. I wonder if there will be performance benefits.

**Comment by benjeffery** [comment]
Don't think there will be, as the hidden components were never placed in the react hierarchy.
