### ISSUE TITLE
Filter production articles to those with "live" tag

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#366]
_From @benjeffery on September 24, 2018 10:43_

For both front page and feed index list.

_Copied from original issue: cggh/panoptes#1185_

**Comment by benjeffery** [comment]
I'm approaching this by adding a `hiddenTags` prop to FeedIndex.

**Comment by leehart** [comment]
`hiddenTag` only supports one tag, but still satisfies the issue (and is MVP, FTW).
I would have pushed for supporting multiple tags, but maybe that's over-engineering!
